name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]


    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up caches
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ matrix.python-version }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e ".[dev]"

      - name: Format with black
        run: |
          black .

      - name: Lint with ruff
        run: |
          ruff .

      - name: Static type check with mypy
        run: |
          mypy --verbose --strict --install-types --non-interactive src test examples

      - name: Test with pytest
        run: |
          PYTHONPATH=src pytest --cov=src test --cov-branch

      - name: Build docs
        run: |
          pdoc --html --output-dir docs --force src/$(basename $(pwd))
          mv docs/*/* docs/
